name: Lint & Test
on:
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'revive.toml'
      - '.github/workflows/lint-test.yaml'
  pull_request:
    types: [opened, edited, synchronize, reopened]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'revive.toml'
      - '.github/workflows/lint-test.yaml'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run Revive Action
      uses: docker://morphy/revive-action:v1
      with:
        config: revive.toml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check formatting
      run: test -z $(gofmt -l .) || (gofmt -l . && exit 1)
